name: frock_runtime

version: 0.0.1

description: Some common utility classes.

author: frikadelki

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  pedantic: ^1.10.0-nullsafety
