name: dvwd3d_app

description: Simple WebGL demos.

version: 2020.1.0

publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
#  chronosgl: ^3.9.3
  vector_math: ">=2.1.0-nullsafety <3.0.0"

  frock_runtime:
    path: ../aa_frock_runtime

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.10.0-nullsafety
